/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class AllSemesterCourseSequenceCSE extends javax.swing.JFrame {

    /**
     * Creates new form AllSemesterCourseSequence
     */
    public AllSemesterCourseSequenceCSE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToCover = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        first = new javax.swing.JButton();
        second = new javax.swing.JButton();
        third = new javax.swing.JButton();
        fourth = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        title.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title.setText("Years:");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, -1));

        first.setBackground(new java.awt.Color(255, 255, 204));
        first.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        first.setForeground(new java.awt.Color(0, 91, 94));
        first.setText("1st"); // NOI18N
        first.setAlignmentY(0.0F);
        first.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        first.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        first.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        first.setOpaque(false);
        first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstActionPerformed(evt);
            }
        });
        getContentPane().add(first, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, 30));

        second.setBackground(new java.awt.Color(255, 255, 204));
        second.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        second.setForeground(new java.awt.Color(0, 91, 94));
        second.setText("2nd"); // NOI18N
        second.setAlignmentY(0.0F);
        second.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        second.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        second.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        second.setOpaque(false);
        second.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondActionPerformed(evt);
            }
        });
        getContentPane().add(second, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 30));

        third.setBackground(new java.awt.Color(255, 255, 204));
        third.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        third.setForeground(new java.awt.Color(0, 91, 94));
        third.setText("3rd"); // NOI18N
        third.setAlignmentY(0.0F);
        third.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        third.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        third.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        third.setOpaque(false);
        third.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdActionPerformed(evt);
            }
        });
        getContentPane().add(third, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 140, 30));

        fourth.setBackground(new java.awt.Color(255, 255, 204));
        fourth.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        fourth.setForeground(new java.awt.Color(0, 91, 94));
        fourth.setText("4th"); // NOI18N
        fourth.setAlignmentY(0.0F);
        fourth.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fourth.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fourth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fourth.setOpaque(false);
        fourth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourthActionPerformed(evt);
            }
        });
        getContentPane().add(fourth, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, 30));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstActionPerformed
        new firstYearCS().setVisible(true);
        this.setVisible(false);               
    }//GEN-LAST:event_firstActionPerformed

    private void secondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondActionPerformed
        new secondYearCS().setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_secondActionPerformed

    private void thirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdActionPerformed
        new thirdYearCS().setVisible(true);
        this.setVisible(false);        
    }//GEN-LAST:event_thirdActionPerformed

    private void fourthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourthActionPerformed
        new fourthYearCS().setVisible(true);
        this.setVisible(false);      
    }//GEN-LAST:event_fourthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllSemesterCourseSequenceCSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllSemesterCourseSequenceCSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllSemesterCourseSequenceCSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllSemesterCourseSequenceCSE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllSemesterCourseSequenceCSE().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JButton first;
    private javax.swing.JButton fourth;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton second;
    private javax.swing.JButton third;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
