/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class cover extends javax.swing.JFrame {

    /**
     * Creates new form cover
     */
    public cover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        VU = new javax.swing.JLabel();
        dept1 = new javax.swing.JLabel();
        dept2 = new javax.swing.JLabel();
        syllabus = new javax.swing.JLabel();
        syllabus1 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        start.setBackground(new java.awt.Color(255, 255, 204));
        start.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        start.setForeground(new java.awt.Color(0, 91, 94));
        start.setText("Start"); // NOI18N
        start.setAlignmentY(0.0F);
        start.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        start.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        start.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        start.setOpaque(false);
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 30));

        menu.setBackground(new java.awt.Color(255, 255, 204));
        menu.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        menu.setForeground(new java.awt.Color(0, 91, 94));
        menu.setText("Menu"); // NOI18N
        menu.setAlignmentY(0.0F);
        menu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 120, 30));

        VU.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        VU.setText("VARENDRA UNIVERSITY"); // NOI18N
        getContentPane().add(VU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 440, 50));

        dept1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        dept1.setForeground(new java.awt.Color(255, 255, 204));
        dept1.setText("Department of"); // NOI18N
        getContentPane().add(dept1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 160, 30));

        dept2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        dept2.setForeground(new java.awt.Color(255, 255, 204));
        dept2.setText("Computer Science and Engineering"); // NOI18N
        getContentPane().add(dept2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 390, -1));

        syllabus.setFont(new java.awt.Font("Verdana", 1, 55)); // NOI18N
        syllabus.setForeground(new java.awt.Color(153, 27, 0));
        syllabus.setText("SYLLABUS"); // NOI18N
        getContentPane().add(syllabus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 360, 70));

        syllabus1.setFont(new java.awt.Font("Verdana", 1, 56)); // NOI18N
        syllabus1.setForeground(new java.awt.Color(255, 255, 204));
        syllabus1.setText("SYLLABUS"); // NOI18N
        getContentPane().add(syllabus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\Israt Jahan\\Documents\\ssss.png")); // NOI18N
        background.setAlignmentY(0.0F);
        background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 800));

        setSize(new java.awt.Dimension(605, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
    new menu().setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        new menu().setVisible(true);
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cover().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel VU;
    private javax.swing.JLabel background;
    private javax.swing.JLabel dept1;
    private javax.swing.JLabel dept2;
    private javax.swing.JLabel exit;
    private javax.swing.JButton menu;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton start;
    private javax.swing.JLabel syllabus;
    private javax.swing.JLabel syllabus1;
    // End of variables declaration//GEN-END:variables
}
