/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class firstYearCS extends javax.swing.JFrame {

    /**
     * Creates new form firstSem
     */
    public firstYearCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        backToCover = new javax.swing.JButton();
        CSE136 = new javax.swing.JLabel();
        CSE134 = new javax.swing.JLabel();
        CSE133 = new javax.swing.JLabel();
        CSE131 = new javax.swing.JLabel();
        MAT131 = new javax.swing.JLabel();
        CSE124 = new javax.swing.JLabel();
        CSE123 = new javax.swing.JLabel();
        CSE122 = new javax.swing.JLabel();
        CSE121 = new javax.swing.JLabel();
        MAT121 = new javax.swing.JLabel();
        ENG121 = new javax.swing.JLabel();
        CSE112 = new javax.swing.JLabel();
        CSE111 = new javax.swing.JLabel();
        PHY112 = new javax.swing.JLabel();
        PHY111 = new javax.swing.JLabel();
        MAT111 = new javax.swing.JLabel();
        ENG111 = new javax.swing.JLabel();
        thirdSem = new javax.swing.JLabel();
        secondSem = new javax.swing.JLabel();
        firstSem = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        CSE136.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE136.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE136MouseClicked(evt);
            }
        });
        getContentPane().add(CSE136, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 656, 250, 16));

        CSE134.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE134.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE134MouseClicked(evt);
            }
        });
        getContentPane().add(CSE134, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 632, 250, 16));

        CSE133.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE133.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE133MouseClicked(evt);
            }
        });
        getContentPane().add(CSE133, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 608, 250, 16));

        CSE131.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE131.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE131MouseClicked(evt);
            }
        });
        getContentPane().add(CSE131, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 584, 250, 16));

        MAT131.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAT131.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAT131MouseClicked(evt);
            }
        });
        getContentPane().add(MAT131, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 561, 250, 16));

        CSE124.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE124MouseClicked(evt);
            }
        });
        getContentPane().add(CSE124, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 250, 16));

        CSE123.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE123.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE123MouseClicked(evt);
            }
        });
        getContentPane().add(CSE123, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 416, 250, 16));

        CSE122.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE122.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE122MouseClicked(evt);
            }
        });
        getContentPane().add(CSE122, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 392, 250, 16));

        CSE121.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE121.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE121MouseClicked(evt);
            }
        });
        getContentPane().add(CSE121, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 368, 250, 16));

        MAT121.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAT121.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAT121MouseClicked(evt);
            }
        });
        getContentPane().add(MAT121, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 344, 250, 16));

        ENG121.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ENG121.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENG121MouseClicked(evt);
            }
        });
        getContentPane().add(ENG121, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 250, 16));

        CSE112.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE112MouseClicked(evt);
            }
        });
        getContentPane().add(CSE112, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 16));

        CSE111.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE111MouseClicked(evt);
            }
        });
        getContentPane().add(CSE111, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 250, 16));

        PHY112.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PHY112.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHY112MouseClicked(evt);
            }
        });
        getContentPane().add(PHY112, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 152, 250, 16));

        PHY111.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PHY111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PHY111MouseClicked(evt);
            }
        });
        getContentPane().add(PHY111, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 128, 250, 16));

        MAT111.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAT111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAT111MouseClicked(evt);
            }
        });
        getContentPane().add(MAT111, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, 250, 16));

        ENG111.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ENG111.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ENG111MouseClicked(evt);
            }
        });
        getContentPane().add(ENG111, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, 16));

        thirdSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thirdSem.setText("1st Year 3rd Semester");
        getContentPane().add(thirdSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        secondSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondSem.setText("1st Year 2nd Semester");
        getContentPane().add(secondSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        firstSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstSem.setText("1st Year 1st Semester");
        getContentPane().add(firstSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        table3.setAutoCreateRowSorter(true);
        table3.setBackground(new java.awt.Color(0, 102, 102));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setForeground(new java.awt.Color(255, 255, 255));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" MAT 131", " Differential Equations & Special Functions", "       100", "       2", null},
                {" CSE 131", " Discrete Mathematics", "       100", "       3", null},
                {" CSE133", " Object Oriented Programming", "       100", "       3", null},
                {" CSE 134", " Object Oriented Programming Lab", "       100", "       1", null},
                {" CSE 136", " Software Development Lab I", "       100", "       3", null},
                {null, "                                                      Total", "       600", "       11.5", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table3.setToolTipText("");
        table3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table3.setAutoscrolls(false);
        table3.setEnabled(false);
        table3.setGridColor(new java.awt.Color(204, 204, 255));
        table3.setOpaque(false);
        table3.setRowHeight(24);
        table3.setRowMargin(2);
        table3.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane5.setViewportView(table3);
        table3.getColumnModel().getColumn(0).setPreferredWidth(3);
        table3.getColumnModel().getColumn(1).setPreferredWidth(200);
        table3.getColumnModel().getColumn(2).setPreferredWidth(10);
        table3.getColumnModel().getColumn(3).setPreferredWidth(1);
        table3.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 530, 180));

        table2.setAutoCreateRowSorter(true);
        table2.setBackground(new java.awt.Color(0, 102, 102));
        table2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table2.setForeground(new java.awt.Color(255, 255, 255));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ENG 121", " English Foundation II", "       100", "       2", null},
                {" MAT121  ", " Coordinate Geometry & Vector Analysis", "       100", "       3", null},
                {" CSE 121", " Electric Circuit", "       100", "       3", null},
                {" CSE 122", " Electric Circuit Lab", "       100", "       1", null},
                {" CSE 123", " Structured Programming Language", "       100", "       3", null},
                {" CSE 124", " Structured Programming Language Lab", "       100", "       1.5", null},
                {null, "                                                      Total", "       600", "       13.5", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "     Page"
            }
        ));
        table2.setToolTipText("");
        table2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table2.setAutoscrolls(false);
        table2.setEnabled(false);
        table2.setGridColor(new java.awt.Color(204, 204, 255));
        table2.setOpaque(false);
        table2.setRowHeight(24);
        table2.setRowMargin(2);
        table2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(table2);
        table2.getColumnModel().getColumn(0).setPreferredWidth(3);
        table2.getColumnModel().getColumn(1).setPreferredWidth(200);
        table2.getColumnModel().getColumn(2).setPreferredWidth(10);
        table2.getColumnModel().getColumn(3).setPreferredWidth(1);
        table2.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 530, 200));

        table1.setAutoCreateRowSorter(true);
        table1.setBackground(new java.awt.Color(0, 102, 102));
        table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ENG 111", " English Foundation I", "       100", "        2", null},
                {" MAT 111", " Diffferential and Integral Calculas", "       100", "        3", null},
                {" PHY 111", " Physics I", "       100", "        3", null},
                {" PHY 112", " Physics I Lab", "       100", "        1", null},
                {" CSE 111", " Computer Fundamental", "       100", "        3", null},
                {" CSE 112", " Computer Application Lab", "       100", "        1", null},
                {null, "                                                      Total", "       600", "        13", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table1.setToolTipText("");
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table1.setAutoscrolls(false);
        table1.setEnabled(false);
        table1.setGridColor(new java.awt.Color(204, 204, 255));
        table1.setOpaque(false);
        table1.setRowHeight(24);
        table1.setRowMargin(2);
        table1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(table1);
        table1.getColumnModel().getColumn(0).setPreferredWidth(3);
        table1.getColumnModel().getColumn(1).setPreferredWidth(200);
        table1.getColumnModel().getColumn(2).setPreferredWidth(10);
        table1.getColumnModel().getColumn(3).setPreferredWidth(1);
        table1.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 530, 200));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void ENG111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENG111MouseClicked
    new ENG111().setVisible(true);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ENG111MouseClicked

    private void MAT111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAT111MouseClicked
       new MAT111().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_MAT111MouseClicked

    private void PHY111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHY111MouseClicked
        new PHY111().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_PHY111MouseClicked

    private void PHY112MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PHY112MouseClicked
        new PHY112().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_PHY112MouseClicked

    private void CSE111MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE111MouseClicked
        new CSE111().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE111MouseClicked

    private void CSE112MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE112MouseClicked
        new CSE112().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE112MouseClicked

    private void CSE124MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE124MouseClicked
        new CSE124().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE124MouseClicked

    private void CSE123MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE123MouseClicked
        new CSE123().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE123MouseClicked

    private void CSE122MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE122MouseClicked
        new CSE122().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE122MouseClicked

    private void CSE121MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE121MouseClicked
        new CSE121().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE121MouseClicked

    private void MAT121MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAT121MouseClicked
        new MAT121().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_MAT121MouseClicked

    private void ENG121MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ENG121MouseClicked
        new ENG121().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ENG121MouseClicked

    private void CSE136MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE136MouseClicked
        new CSE136().setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_CSE136MouseClicked

    private void CSE134MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE134MouseClicked
        new CSE134().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE134MouseClicked

    private void CSE133MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE133MouseClicked
        new CSE133().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE133MouseClicked

    private void CSE131MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE131MouseClicked
        new CSE131().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE131MouseClicked

    private void MAT131MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAT131MouseClicked
        new MAT131().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_MAT131MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(firstYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(firstYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(firstYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(firstYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new firstYearCS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSE111;
    private javax.swing.JLabel CSE112;
    private javax.swing.JLabel CSE121;
    private javax.swing.JLabel CSE122;
    private javax.swing.JLabel CSE123;
    private javax.swing.JLabel CSE124;
    private javax.swing.JLabel CSE131;
    private javax.swing.JLabel CSE133;
    private javax.swing.JLabel CSE134;
    private javax.swing.JLabel CSE136;
    private javax.swing.JLabel ENG111;
    private javax.swing.JLabel ENG121;
    private javax.swing.JLabel MAT111;
    private javax.swing.JLabel MAT121;
    private javax.swing.JLabel MAT131;
    private javax.swing.JLabel PHY111;
    private javax.swing.JLabel PHY112;
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstSem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel secondSem;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JLabel thirdSem;
    // End of variables declaration//GEN-END:variables
}
