/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class fourthYearCS extends javax.swing.JFrame {

    /**
     * Creates new form fourthYearCS
     */
    public fourthYearCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secondSem = new javax.swing.JLabel();
        CSE4316 = new javax.swing.JLabel();
        OptionIIL = new javax.swing.JLabel();
        CSE4212 = new javax.swing.JLabel();
        CSE413 = new javax.swing.JLabel();
        CSE324 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        OptionIIIT = new javax.swing.JLabel();
        OptionIT = new javax.swing.JLabel();
        OptionIIT = new javax.swing.JLabel();
        OptionIIIL = new javax.swing.JLabel();
        CSE411 = new javax.swing.JLabel();
        CSE416 = new javax.swing.JLabel();
        firstSem = new javax.swing.JLabel();
        CSE418 = new javax.swing.JLabel();
        CSE432 = new javax.swing.JLabel();
        CSE421 = new javax.swing.JLabel();
        CSE431 = new javax.swing.JLabel();
        backToCover = new javax.swing.JButton();
        OptionIL = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        CSE415 = new javax.swing.JLabel();
        CSE422 = new javax.swing.JLabel();
        thirdSem = new javax.swing.JLabel();
        CSE423 = new javax.swing.JLabel();
        CSE414 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        secondSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondSem.setText("4th Year 2nd Semester");
        getContentPane().add(secondSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        CSE4316.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE4316.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE4316MouseClicked(evt);
            }
        });
        getContentPane().add(CSE4316, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 673, 240, 16));

        OptionIIL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionIILMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 602, 230, 16));

        CSE4212.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE4212.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE4212MouseClicked(evt);
            }
        });
        getContentPane().add(CSE4212, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 434, 230, 16));

        CSE413.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE413.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE413MouseClicked(evt);
            }
        });
        getContentPane().add(CSE413, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, 250, 16));

        CSE324.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE324.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE324MouseClicked(evt);
            }
        });
        getContentPane().add(CSE324, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 363, 240, 16));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        OptionIIIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIIIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionIIITMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIIIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 626, 240, 16));

        OptionIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionITMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 386, 230, 16));

        OptionIIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionIITMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 578, 230, 16));

        OptionIIIL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIIIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionIIILMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIIIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, 240, 16));

        CSE411.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE411.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE411MouseClicked(evt);
            }
        });
        getContentPane().add(CSE411, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, 16));

        CSE416.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE416.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE416MouseClicked(evt);
            }
        });
        getContentPane().add(CSE416, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 250, 16));

        firstSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstSem.setText("4th Year 1st Semester");
        getContentPane().add(firstSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        CSE418.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE418.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE418MouseClicked(evt);
            }
        });
        getContentPane().add(CSE418, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 16));

        CSE432.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE432.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE432MouseClicked(evt);
            }
        });
        getContentPane().add(CSE432, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 554, 230, 16));

        CSE421.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE421.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE421MouseClicked(evt);
            }
        });
        getContentPane().add(CSE421, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 240, 16));

        CSE431.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE431.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE431MouseClicked(evt);
            }
        });
        getContentPane().add(CSE431, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 240, 16));

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        OptionIL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OptionIL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptionILMouseClicked(evt);
            }
        });
        getContentPane().add(OptionIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 230, 16));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        CSE415.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE415.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE415MouseClicked(evt);
            }
        });
        getContentPane().add(CSE415, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 152, 250, 16));

        CSE422.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE422.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE422MouseClicked(evt);
            }
        });
        getContentPane().add(CSE422, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 314, 230, 16));

        thirdSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thirdSem.setText("1st Year 3rd Semester");
        getContentPane().add(thirdSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        CSE423.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE423.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE423MouseClicked(evt);
            }
        });
        getContentPane().add(CSE423, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 338, 240, 16));

        CSE414.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE414.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE414MouseClicked(evt);
            }
        });
        getContentPane().add(CSE414, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 128, 250, 16));

        table.setAutoCreateRowSorter(true);
        table.setBackground(new java.awt.Color(0, 102, 102));
        table.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" CSE 421", "Computer Graphics ", "       100", "       3", null},
                {" CSE 422", "Computer Graphics  Lab", "       100", "       1", null},
                {" CSE 423", "Digital Image Processing", "       100", "       3", null},
                {" CSE 424", "Digital Image Processing Lab", "       100", "       1", null},
                {" Option I (T)", "Theory: Should be selected from Table-I ", "       100", "       3", null},
                {" Option I (L)", "Lab course based on Option-I (T)", "       100", "       1", null},
                {" CSE 4212", "Project or Thesis with Seminar Part II", "       100", "       1", null},
                {null, "                                               Total", "       600", "       13.5", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "     Page"
            }
        ));
        table.setToolTipText("");
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table.setAutoscrolls(false);
        table.setEnabled(false);
        table.setGridColor(new java.awt.Color(204, 204, 255));
        table.setOpaque(false);
        table.setRowHeight(24);
        table.setRowMargin(2);
        table.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(table);
        table.getColumnModel().getColumn(1).setPreferredWidth(200);
        table.getColumnModel().getColumn(2).setPreferredWidth(10);
        table.getColumnModel().getColumn(3).setPreferredWidth(1);
        table.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 530, 220));

        table3.setAutoCreateRowSorter(true);
        table3.setBackground(new java.awt.Color(0, 102, 102));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setForeground(new java.awt.Color(255, 255, 255));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" CSE 431", "Cryptography and Network Security", "       100", "       3", null},
                {" CSE 432", "Cryptography and Network Security Lab", "       100", "       1", null},
                {" Option II(T)", " Object Oriented Programming", "       100", "       3", null},
                {" Option II(L)", "Lab course based on Option-II (T)", "       100", "       1", null},
                {" Option III(T)", "Theory: Should be selected from Table-II", "       100", "       3", null},
                {" Option III(L)", "Lab course based on Option-III (T)", "       100", "       1", null},
                {" CSE 4316", "Project or Thesis with Seminar Part III", "       100", "       1", null},
                {null, "                                                Total", "       600", "       13", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table3.setToolTipText("");
        table3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table3.setAutoscrolls(false);
        table3.setEnabled(false);
        table3.setGridColor(new java.awt.Color(204, 204, 255));
        table3.setOpaque(false);
        table3.setRowHeight(24);
        table3.setRowMargin(2);
        table3.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane5.setViewportView(table3);
        table3.getColumnModel().getColumn(1).setPreferredWidth(200);
        table3.getColumnModel().getColumn(2).setPreferredWidth(10);
        table3.getColumnModel().getColumn(3).setPreferredWidth(1);
        table3.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 530, 220));

        table1.setAutoCreateRowSorter(true);
        table1.setBackground(new java.awt.Color(0, 102, 102));
        table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" CSE 411", "System Analysis and Design ", "       100", "        3", null},
                {" CSE 413", "Artificial Intelligence", "       100", "        3", null},
                {" CSE 414", "Artificial Intelligence Lab", "       100", "        1", null},
                {" CSE 415", "Digital Signal Processing", "       100", "        3", null},
                {" CSE 416", "Digital Signal Processing Lab", "       100", "        1", null},
                {" CSE 418", "Project or Thesis with Seminar Part I ", "       100", "        1", null},
                {null, "                                                      Total", "       600", "        12", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table1.setToolTipText("");
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table1.setAutoscrolls(false);
        table1.setEnabled(false);
        table1.setGridColor(new java.awt.Color(204, 204, 255));
        table1.setOpaque(false);
        table1.setRowHeight(24);
        table1.setRowMargin(2);
        table1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(table1);
        table1.getColumnModel().getColumn(0).setPreferredWidth(3);
        table1.getColumnModel().getColumn(1).setPreferredWidth(200);
        table1.getColumnModel().getColumn(2).setPreferredWidth(10);
        table1.getColumnModel().getColumn(3).setPreferredWidth(1);
        table1.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 530, 200));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CSE413MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE413MouseClicked
             // TODO add your handling code here:
    }//GEN-LAST:event_CSE413MouseClicked

    private void CSE324MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE324MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE324MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void OptionIIITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionIIITMouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_OptionIIITMouseClicked

    private void OptionITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionITMouseClicked
             // TODO add your handling code here:
    }//GEN-LAST:event_OptionITMouseClicked

    private void OptionIITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionIITMouseClicked
               // TODO add your handling code here:
    }//GEN-LAST:event_OptionIITMouseClicked

    private void OptionIIILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionIIILMouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_OptionIIILMouseClicked

    private void CSE411MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE411MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE411MouseClicked

    private void CSE416MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE416MouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_CSE416MouseClicked

    private void CSE418MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE418MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE418MouseClicked

    private void CSE432MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE432MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE432MouseClicked

    private void CSE421MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE421MouseClicked
             // TODO add your handling code here:
    }//GEN-LAST:event_CSE421MouseClicked

    private void CSE431MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE431MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE431MouseClicked

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void OptionILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionILMouseClicked
            // TODO add your handling code here:
    }//GEN-LAST:event_OptionILMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void CSE415MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE415MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CSE415MouseClicked

    private void CSE422MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE422MouseClicked
                // TODO add your handling code here:
    }//GEN-LAST:event_CSE422MouseClicked

    private void CSE423MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE423MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE423MouseClicked

    private void CSE414MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE414MouseClicked
              // TODO add your handling code here:
    }//GEN-LAST:event_CSE414MouseClicked

    private void CSE4212MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE4212MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CSE4212MouseClicked

    private void OptionIILMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptionIILMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OptionIILMouseClicked

    private void CSE4316MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE4316MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CSE4316MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fourthYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fourthYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fourthYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fourthYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fourthYearCS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSE324;
    private javax.swing.JLabel CSE411;
    private javax.swing.JLabel CSE413;
    private javax.swing.JLabel CSE414;
    private javax.swing.JLabel CSE415;
    private javax.swing.JLabel CSE416;
    private javax.swing.JLabel CSE418;
    private javax.swing.JLabel CSE421;
    private javax.swing.JLabel CSE4212;
    private javax.swing.JLabel CSE422;
    private javax.swing.JLabel CSE423;
    private javax.swing.JLabel CSE431;
    private javax.swing.JLabel CSE4316;
    private javax.swing.JLabel CSE432;
    private javax.swing.JLabel OptionIIIL;
    private javax.swing.JLabel OptionIIIT;
    private javax.swing.JLabel OptionIIL;
    private javax.swing.JLabel OptionIIT;
    private javax.swing.JLabel OptionIL;
    private javax.swing.JLabel OptionIT;
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstSem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel secondSem;
    private javax.swing.JTable table;
    private javax.swing.JTable table1;
    private javax.swing.JTable table3;
    private javax.swing.JLabel thirdSem;
    // End of variables declaration//GEN-END:variables
}
