/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backToCover = new javax.swing.JButton();
        next = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        pDetails = new javax.swing.JButton();
        gSystem = new javax.swing.JButton();
        CGPA = new javax.swing.JButton();
        pEvaluation = new javax.swing.JButton();
        distriOfCourses = new javax.swing.JButton();
        allSemCourse = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        next.setBackground(new java.awt.Color(0, 102, 102));
        next.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("Next");
        next.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        next.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 60, 30));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        pDetails.setBackground(new java.awt.Color(255, 255, 204));
        pDetails.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        pDetails.setForeground(new java.awt.Color(0, 91, 94));
        pDetails.setText("Program Details"); // NOI18N
        pDetails.setAlignmentY(0.0F);
        pDetails.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pDetails.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pDetails.setOpaque(false);
        pDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(pDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 380, 30));

        gSystem.setBackground(new java.awt.Color(255, 255, 204));
        gSystem.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        gSystem.setForeground(new java.awt.Color(0, 91, 94));
        gSystem.setText("Grading System"); // NOI18N
        gSystem.setAlignmentY(0.0F);
        gSystem.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gSystem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gSystem.setOpaque(false);
        gSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gSystemActionPerformed(evt);
            }
        });
        getContentPane().add(gSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 380, 30));

        CGPA.setBackground(new java.awt.Color(255, 255, 204));
        CGPA.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        CGPA.setForeground(new java.awt.Color(0, 91, 94));
        CGPA.setText("CGPA Calculation"); // NOI18N
        CGPA.setAlignmentY(0.0F);
        CGPA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CGPA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CGPA.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CGPA.setOpaque(false);
        CGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGPAActionPerformed(evt);
            }
        });
        getContentPane().add(CGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 380, 30));

        pEvaluation.setBackground(new java.awt.Color(255, 255, 204));
        pEvaluation.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        pEvaluation.setForeground(new java.awt.Color(0, 91, 94));
        pEvaluation.setText("Performance Evaluation"); // NOI18N
        pEvaluation.setAlignmentY(0.0F);
        pEvaluation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pEvaluation.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pEvaluation.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pEvaluation.setOpaque(false);
        pEvaluation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pEvaluationActionPerformed(evt);
            }
        });
        getContentPane().add(pEvaluation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 380, 30));

        distriOfCourses.setBackground(new java.awt.Color(255, 255, 204));
        distriOfCourses.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        distriOfCourses.setForeground(new java.awt.Color(0, 91, 94));
        distriOfCourses.setText("Distribution of Courses"); // NOI18N
        distriOfCourses.setAlignmentY(0.0F);
        distriOfCourses.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        distriOfCourses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        distriOfCourses.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        distriOfCourses.setOpaque(false);
        distriOfCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distriOfCoursesActionPerformed(evt);
            }
        });
        getContentPane().add(distriOfCourses, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 380, 30));

        allSemCourse.setBackground(new java.awt.Color(255, 255, 204));
        allSemCourse.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        allSemCourse.setForeground(new java.awt.Color(0, 91, 94));
        allSemCourse.setText("All Semester Course Sequence"); // NOI18N
        allSemCourse.setAlignmentY(0.0F);
        allSemCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allSemCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        allSemCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        allSemCourse.setOpaque(false);
        allSemCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSemCourseActionPerformed(evt);
            }
        });
        getContentPane().add(allSemCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 380, 30));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        setSize(new java.awt.Dimension(605, 739));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pDetailsActionPerformed
        new ProgramDetails().setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_pDetailsActionPerformed

    private void gSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gSystemActionPerformed
        new GradingSystem().setVisible(true);
        this.setVisible(false);  
    }//GEN-LAST:event_gSystemActionPerformed

    private void CGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGPAActionPerformed
        new CGPA().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CGPAActionPerformed

    private void pEvaluationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pEvaluationActionPerformed
        new PerformanceEvaluation().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_pEvaluationActionPerformed

    private void distriOfCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distriOfCoursesActionPerformed
        new DistributionOfCourses().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_distriOfCoursesActionPerformed

    private void allSemCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSemCourseActionPerformed
        new AllSemesterCourseSequenceCSE().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_allSemCourseActionPerformed

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
    new ProgramDetails().setVisible(true);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CGPA;
    private javax.swing.JButton allSemCourse;
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JButton distriOfCourses;
    private javax.swing.JLabel exit;
    private javax.swing.JButton gSystem;
    private javax.swing.JLabel minimize;
    private javax.swing.JButton next;
    private javax.swing.JButton pDetails;
    private javax.swing.JButton pEvaluation;
    // End of variables declaration//GEN-END:variables
}
