/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class secondYearCS extends javax.swing.JFrame {

    /**
     * Creates new form secondYearCS
     */
    public secondYearCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSE236 = new javax.swing.JLabel();
        CSE211 = new javax.swing.JLabel();
        CSE224 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        secondSem = new javax.swing.JLabel();
        CSE231 = new javax.swing.JLabel();
        CSE225 = new javax.swing.JLabel();
        CSE233 = new javax.swing.JLabel();
        STA231 = new javax.swing.JLabel();
        MAT211 = new javax.swing.JLabel();
        CSE214 = new javax.swing.JLabel();
        firstSem = new javax.swing.JLabel();
        CSE232 = new javax.swing.JLabel();
        GED221 = new javax.swing.JLabel();
        CSE234 = new javax.swing.JLabel();
        backToCover = new javax.swing.JButton();
        CSE226 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        CSE213 = new javax.swing.JLabel();
        CSE221 = new javax.swing.JLabel();
        thirdSem = new javax.swing.JLabel();
        CSE223 = new javax.swing.JLabel();
        CSE212 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        table4 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CSE236.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE236.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE236MouseClicked(evt);
            }
        });
        getContentPane().add(CSE236, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 670, 250, 16));

        CSE211.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE211.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE211MouseClicked(evt);
            }
        });
        getContentPane().add(CSE211, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, 250, 16));

        CSE224.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE224.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE224MouseClicked(evt);
            }
        });
        getContentPane().add(CSE224, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 392, 250, 16));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        secondSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondSem.setText("2nd Year 2nd Semester");
        getContentPane().add(secondSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        CSE231.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE231.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE231MouseClicked(evt);
            }
        });
        getContentPane().add(CSE231, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 574, 250, 16));

        CSE225.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE225.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE225MouseClicked(evt);
            }
        });
        getContentPane().add(CSE225, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 416, 250, 16));

        CSE233.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE233.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE233MouseClicked(evt);
            }
        });
        getContentPane().add(CSE233, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 622, 250, 16));

        STA231.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        STA231.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STA231MouseClicked(evt);
            }
        });
        getContentPane().add(STA231, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 250, 16));

        MAT211.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MAT211.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MAT211MouseClicked(evt);
            }
        });
        getContentPane().add(MAT211, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, 16));

        CSE214.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE214.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE214MouseClicked(evt);
            }
        });
        getContentPane().add(CSE214, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 250, 16));

        firstSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstSem.setText("2nd Year 1st Semester");
        getContentPane().add(firstSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        CSE232.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE232.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE232MouseClicked(evt);
            }
        });
        getContentPane().add(CSE232, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 598, 250, 16));

        GED221.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GED221.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GED221MouseClicked(evt);
            }
        });
        getContentPane().add(GED221, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 250, 16));

        CSE234.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE234.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE234MouseClicked(evt);
            }
        });
        getContentPane().add(CSE234, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 646, 250, 16));

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        CSE226.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE226.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE226MouseClicked(evt);
            }
        });
        getContentPane().add(CSE226, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 250, 16));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        CSE213.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE213.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE213MouseClicked(evt);
            }
        });
        getContentPane().add(CSE213, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 152, 250, 16));

        CSE221.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE221.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE221MouseClicked(evt);
            }
        });
        getContentPane().add(CSE221, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 344, 250, 16));

        thirdSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thirdSem.setText("2nd Year 3rd Semester");
        getContentPane().add(thirdSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, -1, -1));

        CSE223.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE223.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE223MouseClicked(evt);
            }
        });
        getContentPane().add(CSE223, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 368, 250, 16));

        CSE212.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE212.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE212MouseClicked(evt);
            }
        });
        getContentPane().add(CSE212, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 128, 250, 16));

        table2.setAutoCreateRowSorter(true);
        table2.setBackground(new java.awt.Color(0, 102, 102));
        table2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table2.setForeground(new java.awt.Color(255, 255, 255));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" GED 221", "Bangladesh Culture & Heritage Studies ", "       100", "       2", null},
                {" CSE 221  ", "Software Engineering ", "       100", "       3", null},
                {" CSE 223", "Electronic Devices and Circuits ", "       100", "       3", null},
                {" CSE 224", "Electronic Devices and Circuits Lab", "       100", "       1", null},
                {" CSE 225", "Algorithms ", "       100", "       3", null},
                {" CSE 226", "Algorithms  LAB", "       100", "       1.5", null},
                {null, "                                                      Total", "       600", "       13.5", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "     Page"
            }
        ));
        table2.setToolTipText("");
        table2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table2.setAutoscrolls(false);
        table2.setEnabled(false);
        table2.setGridColor(new java.awt.Color(204, 204, 255));
        table2.setOpaque(false);
        table2.setRowHeight(24);
        table2.setRowMargin(2);
        table2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(table2);
        table2.getColumnModel().getColumn(0).setPreferredWidth(3);
        table2.getColumnModel().getColumn(1).setPreferredWidth(200);
        table2.getColumnModel().getColumn(2).setPreferredWidth(10);
        table2.getColumnModel().getColumn(3).setPreferredWidth(1);
        table2.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 530, 200));

        table3.setAutoCreateRowSorter(true);
        table3.setBackground(new java.awt.Color(0, 102, 102));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setForeground(new java.awt.Color(255, 255, 255));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" STA 231", "Basic Statistics and Probability ", "       100", "       3", null},
                {" CSE 231", "Digital Logic Design", "       100", "       3", null},
                {" CSE 232", "Digital Logic Design LAB", "       100", "       1", null},
                {" CSE 233", "Computer Networks", "       100", "       3", null},
                {" CSE 234", "Computer Networks  LAB", "       100", "       1", null},
                {" CSE 236", "Software Development Lab II", "       100", "       1", null},
                {"", "                                                      Total", "       600", "       12", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table3.setToolTipText("");
        table3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table3.setAutoscrolls(false);
        table3.setEnabled(false);
        table3.setGridColor(new java.awt.Color(204, 204, 255));
        table3.setOpaque(false);
        table3.setRowHeight(24);
        table3.setRowMargin(2);
        table3.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane5.setViewportView(table3);
        table3.getColumnModel().getColumn(0).setPreferredWidth(3);
        table3.getColumnModel().getColumn(1).setPreferredWidth(200);
        table3.getColumnModel().getColumn(2).setPreferredWidth(10);
        table3.getColumnModel().getColumn(3).setPreferredWidth(1);
        table3.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 530, 200));

        table4.setAutoCreateRowSorter(true);
        table4.setBackground(new java.awt.Color(0, 102, 102));
        table4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table4.setForeground(new java.awt.Color(255, 255, 255));
        table4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" MAT 211", "Linear Algebra and Complex Variables", "       100", "        3", null},
                {" CSE 211", "Data Structures", "       100", "        3", null},
                {" CSE 212", "Data Structures LAB", "       100", "        1.5", null},
                {" CSE 213", "Object Oriented Design and Design Patterns", "       100", "        3", null},
                {" CSE 214", "Object Oriented Design and Design Patterns LAB", "       100", "        1.5", null},
                {null, "                                                      Total", "       500", "        12", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table4.setToolTipText("");
        table4.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table4.setAutoscrolls(false);
        table4.setEnabled(false);
        table4.setGridColor(new java.awt.Color(204, 204, 255));
        table4.setOpaque(false);
        table4.setRowHeight(24);
        table4.setRowMargin(2);
        table4.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane4.setViewportView(table4);
        table4.getColumnModel().getColumn(0).setPreferredWidth(3);
        table4.getColumnModel().getColumn(1).setPreferredWidth(200);
        table4.getColumnModel().getColumn(2).setPreferredWidth(10);
        table4.getColumnModel().getColumn(3).setPreferredWidth(1);
        table4.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 530, 180));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CSE211MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE211MouseClicked
        new CSE211().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE211MouseClicked

    private void CSE224MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE224MouseClicked
        new CSE224().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE224MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void CSE231MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE231MouseClicked
        new CSE231().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE231MouseClicked

    private void CSE225MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE225MouseClicked
        new CSE225().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE225MouseClicked

    private void CSE233MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE233MouseClicked
        new CSE233().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE233MouseClicked

    private void STA231MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STA231MouseClicked
        new STA231().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_STA231MouseClicked

    private void MAT211MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MAT211MouseClicked
        new MAT211().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_MAT211MouseClicked

    private void CSE214MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE214MouseClicked
        new CSE214().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE214MouseClicked

    private void CSE232MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE232MouseClicked
        new CSE232().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE232MouseClicked

    private void GED221MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GED221MouseClicked
        new GED221().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_GED221MouseClicked

    private void CSE234MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE234MouseClicked
        new CSE234().setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_CSE234MouseClicked

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void CSE226MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE226MouseClicked
        new CSE226().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE226MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void CSE213MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE213MouseClicked
        new CSE213().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_CSE213MouseClicked

    private void CSE221MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE221MouseClicked
        new CSE221().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE221MouseClicked

    private void CSE223MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE223MouseClicked
        new CSE223().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE223MouseClicked

    private void CSE212MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE212MouseClicked
        new CSE212().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE212MouseClicked

    private void CSE236MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE236MouseClicked
        new CSE236().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE236MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(secondYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(secondYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(secondYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(secondYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new secondYearCS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CSE211;
    private javax.swing.JLabel CSE212;
    private javax.swing.JLabel CSE213;
    private javax.swing.JLabel CSE214;
    private javax.swing.JLabel CSE221;
    private javax.swing.JLabel CSE223;
    private javax.swing.JLabel CSE224;
    private javax.swing.JLabel CSE225;
    private javax.swing.JLabel CSE226;
    private javax.swing.JLabel CSE231;
    private javax.swing.JLabel CSE232;
    private javax.swing.JLabel CSE233;
    private javax.swing.JLabel CSE234;
    private javax.swing.JLabel CSE236;
    private javax.swing.JLabel GED221;
    private javax.swing.JLabel MAT211;
    private javax.swing.JLabel STA231;
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstSem;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel secondSem;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JTable table4;
    private javax.swing.JLabel thirdSem;
    // End of variables declaration//GEN-END:variables
}
