/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package miniSyllabus;

/**
 *
 * @author Israt Jahan
 */
public class thirdYearCS extends javax.swing.JFrame {

    /**
     * Creates new form thirdYearCS
     */
    public thirdYearCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CSE336 = new javax.swing.JLabel();
        CSE311 = new javax.swing.JLabel();
        CSE324 = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        secondSem = new javax.swing.JLabel();
        CSE331 = new javax.swing.JLabel();
        CSE325 = new javax.swing.JLabel();
        CSE333 = new javax.swing.JLabel();
        ECO331 = new javax.swing.JLabel();
        ACC311 = new javax.swing.JLabel();
        CSE314 = new javax.swing.JLabel();
        firstSem = new javax.swing.JLabel();
        CSE315 = new javax.swing.JLabel();
        CSE332 = new javax.swing.JLabel();
        LAW321 = new javax.swing.JLabel();
        CSE334 = new javax.swing.JLabel();
        backToCover = new javax.swing.JButton();
        CSE326 = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        CSE313 = new javax.swing.JLabel();
        CSE321 = new javax.swing.JLabel();
        thirdSem = new javax.swing.JLabel();
        CSE323 = new javax.swing.JLabel();
        CSE312 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        table3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CSE336.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE336.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE336MouseClicked(evt);
            }
        });
        getContentPane().add(CSE336, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 660, 250, 16));

        CSE311.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE311.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE311MouseClicked(evt);
            }
        });
        getContentPane().add(CSE311, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 104, 250, 16));

        CSE324.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE324.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE324MouseClicked(evt);
            }
        });
        getContentPane().add(CSE324, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 392, 250, 16));

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/minimize final.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        secondSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        secondSem.setText("3rd Year 2nd Semester");
        getContentPane().add(secondSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        CSE331.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE331.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE331MouseClicked(evt);
            }
        });
        getContentPane().add(CSE331, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 564, 250, 16));

        CSE325.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE325.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE325MouseClicked(evt);
            }
        });
        getContentPane().add(CSE325, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 416, 250, 16));

        CSE333.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE333.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE333MouseClicked(evt);
            }
        });
        getContentPane().add(CSE333, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 612, 250, 16));

        ECO331.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ECO331.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ECO331MouseClicked(evt);
            }
        });
        getContentPane().add(ECO331, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 250, 16));

        ACC311.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ACC311.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ACC311MouseClicked(evt);
            }
        });
        getContentPane().add(ACC311, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 250, 16));

        CSE314.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE314.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE314MouseClicked(evt);
            }
        });
        getContentPane().add(CSE314, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 176, 250, 16));

        firstSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstSem.setText("3rd Year 1st Semester");
        getContentPane().add(firstSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        CSE315.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE315.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE315MouseClicked(evt);
            }
        });
        getContentPane().add(CSE315, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 16));

        CSE332.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE332.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE332MouseClicked(evt);
            }
        });
        getContentPane().add(CSE332, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 588, 250, 16));

        LAW321.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LAW321.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LAW321MouseClicked(evt);
            }
        });
        getContentPane().add(LAW321, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 250, 16));

        CSE334.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE334.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE334MouseClicked(evt);
            }
        });
        getContentPane().add(CSE334, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 636, 250, 16));

        backToCover.setBackground(new java.awt.Color(0, 102, 102));
        backToCover.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        backToCover.setForeground(new java.awt.Color(255, 255, 255));
        backToCover.setText("cover");
        backToCover.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));
        backToCover.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backToCover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToCoverActionPerformed(evt);
            }
        });
        getContentPane().add(backToCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 60, 30));

        CSE326.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE326.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE326MouseClicked(evt);
            }
        });
        getContentPane().add(CSE326, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 250, 16));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniSyllabus/exit final.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 20));

        CSE313.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE313.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE313MouseClicked(evt);
            }
        });
        getContentPane().add(CSE313, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 152, 250, 16));

        CSE321.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE321.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE321MouseClicked(evt);
            }
        });
        getContentPane().add(CSE321, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 344, 250, 16));

        thirdSem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thirdSem.setText("3rd Year 3rd Semester");
        getContentPane().add(thirdSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        CSE323.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE323.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE323MouseClicked(evt);
            }
        });
        getContentPane().add(CSE323, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 368, 250, 16));

        CSE312.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CSE312.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CSE312MouseClicked(evt);
            }
        });
        getContentPane().add(CSE312, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 128, 250, 16));

        table2.setAutoCreateRowSorter(true);
        table2.setBackground(new java.awt.Color(0, 102, 102));
        table2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table2.setForeground(new java.awt.Color(255, 255, 255));
        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" LAW 321", "Cyber and Intellectual Property Laws", "       100", "       3", null},
                {" CSE 321", "Theory of Computation and Compiler Design", "       100", "       1", null},
                {" CSE 323", "3 Computer Architecture", "       100", "       3", null},
                {" CSE 324", "3 Computer Architecture Lab", "       100", "       1", null},
                {" CSE 325", "E-Commerce and Web Programming", "       100", "       3", null},
                {" CSE 326", "E-Commerce and Web Programming Lab", "       100", "       1", null},
                {null, "                                                      Total", "       600", "       13", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "     Page"
            }
        ));
        table2.setToolTipText("");
        table2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table2.setAutoscrolls(false);
        table2.setEnabled(false);
        table2.setGridColor(new java.awt.Color(204, 204, 255));
        table2.setOpaque(false);
        table2.setRowHeight(24);
        table2.setRowMargin(2);
        table2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(table2);
        table2.getColumnModel().getColumn(0).setPreferredWidth(3);
        table2.getColumnModel().getColumn(1).setPreferredWidth(200);
        table2.getColumnModel().getColumn(2).setPreferredWidth(10);
        table2.getColumnModel().getColumn(3).setPreferredWidth(1);
        table2.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 530, 200));

        table3.setAutoCreateRowSorter(true);
        table3.setBackground(new java.awt.Color(0, 102, 102));
        table3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table3.setForeground(new java.awt.Color(255, 255, 255));
        table3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ECO 331", "31 Economics ", "       100", "       2", null},
                {" CSE 331", "Operating System and System Programming ", "       100", "       3", null},
                {" CSE 332", "Operating System and System Programming Lab", "       100", "       1", null},
                {" CSE 333", "Microprocessor and Assembly Language", "       100", "       3", null},
                {" CSE 334", "Microprocessor and Assembly Language Lab", "       100", "       2", null},
                {" CSE 336", "Software Development Lab III", "       100", "       1", null},
                {null, "                                                      Total", "        600", "       11", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table3.setToolTipText("");
        table3.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table3.setAutoscrolls(false);
        table3.setEnabled(false);
        table3.setGridColor(new java.awt.Color(204, 204, 255));
        table3.setOpaque(false);
        table3.setRowHeight(24);
        table3.setRowMargin(2);
        table3.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane5.setViewportView(table3);
        table3.getColumnModel().getColumn(0).setPreferredWidth(3);
        table3.getColumnModel().getColumn(1).setPreferredWidth(200);
        table3.getColumnModel().getColumn(2).setPreferredWidth(10);
        table3.getColumnModel().getColumn(3).setPreferredWidth(1);
        table3.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 530, 200));

        table1.setAutoCreateRowSorter(true);
        table1.setBackground(new java.awt.Color(0, 102, 102));
        table1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ACC 311", "Industrial Management and Accountancy ", "       100", "        2", null},
                {" CSE 311", "1 Numerical Method ", "       100", "        3", null},
                {" CSE 312", "1 Numerical Method Lab", "       100", "        1", null},
                {" CSE 313", "Database Management System", "       100", "        3", null},
                {" CSE 314", "Database Management System Lab", "       100", "        1.5", null},
                {" CSE 315", "Communication Engineering", "       100", "        3", null},
                {null, "                                                      Total", "       600", "        13.5", null}
            },
            new String [] {
                "     Code", "                            Course Title", "      Marks", "     Credit", "      Page"
            }
        ));
        table1.setToolTipText("");
        table1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        table1.setAutoscrolls(false);
        table1.setEnabled(false);
        table1.setGridColor(new java.awt.Color(204, 204, 255));
        table1.setOpaque(false);
        table1.setRowHeight(24);
        table1.setRowMargin(2);
        table1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(table1);
        table1.getColumnModel().getColumn(0).setPreferredWidth(3);
        table1.getColumnModel().getColumn(1).setPreferredWidth(200);
        table1.getColumnModel().getColumn(2).setPreferredWidth(10);
        table1.getColumnModel().getColumn(3).setPreferredWidth(1);
        table1.getColumnModel().getColumn(4).setPreferredWidth(1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 530, 200));

        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 20));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 605, 739));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CSE311MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE311MouseClicked
        new CSE311().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE311MouseClicked

    private void CSE324MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE324MouseClicked
        new CSE324().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE324MouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(cover.ICONIFIED);        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseClicked

    private void CSE331MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE331MouseClicked
        new CSE331().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE331MouseClicked

    private void CSE325MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE325MouseClicked
        new CSE325().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE325MouseClicked

    private void CSE333MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE333MouseClicked
        new CSE333().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE333MouseClicked

    private void ECO331MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ECO331MouseClicked
        new ECO331().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_ECO331MouseClicked

    private void ACC311MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ACC311MouseClicked
        new ACC311().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_ACC311MouseClicked

    private void CSE314MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE314MouseClicked
        new CSE314().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE314MouseClicked

    private void CSE315MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE315MouseClicked
        new CSE315().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE315MouseClicked

    private void CSE332MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE332MouseClicked
        new CSE332().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_CSE332MouseClicked

    private void LAW321MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LAW321MouseClicked
        new LAW321().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_LAW321MouseClicked

    private void CSE334MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE334MouseClicked
        new CSE334().setVisible(true);
        this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_CSE334MouseClicked

    private void backToCoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToCoverActionPerformed
        new cover().setVisible(true);
        this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_backToCoverActionPerformed

    private void CSE326MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE326MouseClicked
        new CSE326().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE326MouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitMouseClicked

    private void CSE313MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE313MouseClicked
        new CSE313().setVisible(true);
        this.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_CSE313MouseClicked

    private void CSE321MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE321MouseClicked
        new CSE321().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE321MouseClicked

    private void CSE323MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE323MouseClicked
        new CSE323().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE323MouseClicked

    private void CSE312MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE312MouseClicked
        new CSE312().setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_CSE312MouseClicked

    private void CSE336MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSE336MouseClicked
        new CSE336().setVisible(true);
        this.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_CSE336MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(thirdYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(thirdYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(thirdYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(thirdYearCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new thirdYearCS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ACC311;
    private javax.swing.JLabel CSE311;
    private javax.swing.JLabel CSE312;
    private javax.swing.JLabel CSE313;
    private javax.swing.JLabel CSE314;
    private javax.swing.JLabel CSE315;
    private javax.swing.JLabel CSE321;
    private javax.swing.JLabel CSE323;
    private javax.swing.JLabel CSE324;
    private javax.swing.JLabel CSE325;
    private javax.swing.JLabel CSE326;
    private javax.swing.JLabel CSE331;
    private javax.swing.JLabel CSE332;
    private javax.swing.JLabel CSE333;
    private javax.swing.JLabel CSE334;
    private javax.swing.JLabel CSE336;
    private javax.swing.JLabel ECO331;
    private javax.swing.JLabel LAW321;
    private javax.swing.JButton backToCover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel firstSem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel secondSem;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTable table3;
    private javax.swing.JLabel thirdSem;
    // End of variables declaration//GEN-END:variables
}
